### ISSUE TITLE
Please avoid magic numbers, who are these?

### ISSUE THREAD

**Issue by mCodingLLC** [CircuitSacul/mCoding-Bot#2]
https://github.com/CircuitSacul/mCoding-Bot/blob/446546db939b42f6955d8e05029832c774ab0673/app/bot.py#L32

**Comment by circuitsacul** [comment]
Sigmanificient wanted access to owner commands so they did that. The role ids are mine and Sigmanificient's.

I'll add the bot to a team and remove this.

**Comment by circuitsacul** [comment]
I've removed it for now; The owner_ids of a bot give those users access to run commands such as eval. Really only the person hosting the bot should have access. As I am hosting now it makes sense to simply remove.
