### ISSUE TITLE
Use specific permissions

### ISSUE THREAD

**Issue by mCodingLLC** [CircuitSacul/mCoding-Bot#4]
https://github.com/CircuitSacul/mCoding-Bot/blob/990200e0f45002c351f29ea3a727e10e85a20c09/app/bot.py#L13

I'm assuming here that "intents" is discord's wording for "permissions" https://discord.com/developers/docs/topics/gateway#gateway-intents. I think it's a good idea to use the minimal permissions required to get the job done, so if we have a bug it doesn't end up deleting the server or anything like that. It seems like the bot only needs

  - GUILD_ROLE_UPDATE

and maybe some messaging permissions.

**Comment by circuitsacul** [comment]
No it actually needs them all.

**Comment by circuitsacul** [comment]
Hmm nvm, I'll fix that

**Comment by circuitsacul** [comment]
So here are the docs for the Intents class: <https://discordpy.readthedocs.io/en/stable/api.html?highlight=intents#discord.Intents>. Of these, it needs:

guild_messages
guild_reactions
guilds
members
presences

I'll update accordingly
